- pkg:cargo/dependabot-generator@0.1.0
- pkg:cargo/dependabot-generator@0.1.1
- pkg:cargo/dependabot-generator@0.1.2
- pkg:cargo/dependabot-generator@0.1.3
- pkg:cargo/dependabot-generator@1.0.0
- pkg:cargo/dependabot-generator@1.0.1
- pkg:cargo/dependabot-generator@1.1.0
- pkg:cargo/dependabot-generator@1.2.0
- pkg:cargo/dependabot-generator@1.3.0
