- pkg:cargo/bees-prometheus-exporter@0.1.0
- pkg:cargo/bees-prometheus-exporter@0.1.1
- pkg:cargo/bees-prometheus-exporter@0.1.2
- pkg:cargo/bees-prometheus-exporter@0.1.3
- pkg:cargo/bees-prometheus-exporter@1.0.0
- pkg:cargo/bees-prometheus-exporter@2.0.0
