- pkg:cargo/esphome-native-api@0.0.1
- pkg:cargo/esphome-native-api@0.0.2
- pkg:cargo/esphome-native-api@0.0.3
- pkg:cargo/esphome-native-api@1.0.0
- pkg:cargo/esphome-native-api@1.0.1
- pkg:cargo/esphome-native-api@1.0.2
- pkg:cargo/esphome-native-api@1.0.3
- pkg:cargo/esphome-native-api@1.1.0
- pkg:cargo/esphome-native-api@1.1.1
- pkg:cargo/esphome-native-api@1.1.2
- pkg:cargo/esphome-native-api@1.1.3
- pkg:cargo/esphome-native-api@1.1.4
- pkg:cargo/esphome-native-api@1.1.5
- pkg:cargo/esphome-native-api@1.1.6
